In [109]:
print("shree")

shree

In [110]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [111]:
training_features = pd.read_csv(r"C:\Users\Akshay Phatak\Documents\Atharva\ML\IITGuwati_Datascience\dataset and all\training_set_features.csv")
training_features.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [112]:
training_features_copy = training_features.copy()

In [113]:
#training_features= training_features.drop(columns=['employment_industry', 'employment_occupation', 'respondent_id'])
training_features.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [114]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier

In [115]:
categorical_features = ['age_group', 'education', 'race', 'sex', 'income_poverty', 'marital_status', 'rent_or_own', 'employment_status', 'hhs_geo_region', 'census_msa','employment_industry', 'employment_occupation']
numerical_features = [col for col in training_features.columns if col not in categorical_features]

In [116]:
preprocessor = ColumnTransformer(transformers=[('num', StandardScaler(), numerical_features),('cat', OneHotEncoder(), categorical_features)])

In [117]:
numerical_features

['respondent_id',
 'xyz_concern',
 'xyz_knowledge',
 'behavioral_antiviral_meds',
 'behavioral_avoidance',
 'behavioral_face_mask',
 'behavioral_wash_hands',
 'behavioral_large_gatherings',
 'behavioral_outside_home',
 'behavioral_touch_face',
 'doctor_recc_xyz',
 'doctor_recc_seasonal',
 'chronic_med_condition',
 'child_under_6_months',
 'health_worker',
 'health_insurance',
 'opinion_xyz_vacc_effective',
 'opinion_xyz_risk',
 'opinion_xyz_sick_from_vacc',
 'opinion_seas_vacc_effective',
 'opinion_seas_risk',
 'opinion_seas_sick_from_vacc',
 'household_adults',
 'household_children']

In [118]:
scaler = StandardScaler()
training_features[numerical_features] = scaler.fit_transform(training_features[numerical_features])

In [119]:
training_features.head()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,-1.731986,-0.679436,-2.042478,-0.22661,-1.626185,-0.272201,-2.175870,-0.747788,1.401639,0.690311,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,-1.176654,-0.575963,NaN,NaN
1,-1.731856,1.517658,1.193048,-0.22661,0.614936,-0.272201,0.459586,-0.747788,1.401639,0.690311,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",-1.176654,-0.575963,pxcmvdjn,xgwztkwe
2,-1.731727,-0.679436,-0.424715,-0.22661,0.614936,-0.272201,-2.175870,-0.747788,-0.713450,-1.448623,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.477953,-0.575963,rucpziij,xtkaffoo
3,-1.731597,-0.679436,-0.424715,-0.22661,0.614936,-0.272201,0.459586,1.337277,-0.713450,-1.448623,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",-1.176654,-0.575963,NaN,NaN
4,-1.731467,0.419111,-0.424715,-0.22661,0.614936,-0.272201,0.459586,1.337277,-0.713450,0.690311,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",0.150650,-0.575963,wxleyezf,emcorrxb

In [120]:
one_hot_encoder = OneHotEncoder(sparse=False, drop='first')
encoded_features = one_hot_encoder.fit_transform(training_features[categorical_features])
encoded_df = pd.DataFrame(encoded_features, columns=one_hot_encoder.get_feature_names_out(categorical_features))
training_features= pd.concat([training_features.drop(columns=categorical_features), encoded_df], axis=1)

C:\Users\Akshay Phatak\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [121]:
for i in training_features.columns.to_list():
    print(i, training_features[i].isna().sum())
    print(i, training_features[i].isnull().sum())
    print("")

respondent_id 0
respondent_id 0

xyz_concern 92
xyz_concern 92

xyz_knowledge 116
xyz_knowledge 116

behavioral_antiviral_meds 71
behavioral_antiviral_meds 71

behavioral_avoidance 208
behavioral_avoidance 208

behavioral_face_mask 19
behavioral_face_mask 19

behavioral_wash_hands 42
behavioral_wash_hands 42

behavioral_large_gatherings 87
behavioral_large_gatherings 87

behavioral_outside_home 82
behavioral_outside_home 82

behavioral_touch_face 128
behavioral_touch_face 128

doctor_recc_xyz 2160
doctor_recc_xyz 2160

doctor_recc_seasonal 2160
doctor_recc_seasonal 2160

chronic_med_condition 971
chronic_med_condition 971

child_under_6_months 820
child_under_6_months 820

health_worker 804
health_worker 804

health_insurance 12274
health_insurance 12274

opinion_xyz_vacc_effective 391
opinion_xyz_vacc_effective 391

opinion_xyz_risk 388
opinion_xyz_risk 388

opinion_xyz_sick_from_vacc 395
opinion_xyz_sick_from_vacc 395

opinion_seas_vacc_effective 462
opinion_seas_vacc_effective 462

opinion_seas_risk 514
opinion_seas_risk 514

opinion_seas_sick_from_vacc 537
opinion_seas_sick_from_vacc 537

household_adults 249
household_adults 249

household_children 249
household_children 249

age_group_35 - 44 Years 0
age_group_35 - 44 Years 0

age_group_45 - 54 Years 0
age_group_45 - 54 Years 0

age_group_55 - 64 Years 0
age_group_55 - 64 Years 0

age_group_65+ Years 0
age_group_65+ Years 0

education_< 12 Years 0
education_< 12 Years 0

education_College Graduate 0
education_College Graduate 0

education_Some College 0
education_Some College 0

education_nan 0
education_nan 0

race_Hispanic 0
race_Hispanic 0

race_Other or Multiple 0
race_Other or Multiple 0

race_White 0
race_White 0

sex_Male 0
sex_Male 0

income_poverty_> $75,000 0
income_poverty_> $75,000 0

income_poverty_Below Poverty 0
income_poverty_Below Poverty 0

income_poverty_nan 0
income_poverty_nan 0

marital_status_Not Married 0
marital_status_Not Married 0

marital_status_nan 0
marital_status_nan 0

rent_or_own_Rent 0
rent_or_own_Rent 0

rent_or_own_nan 0
rent_or_own_nan 0

employment_status_Not in Labor Force 0
employment_status_Not in Labor Force 0

employment_status_Unemployed 0
employment_status_Unemployed 0

employment_status_nan 0
employment_status_nan 0

hhs_geo_region_bhuqouqj 0
hhs_geo_region_bhuqouqj 0

hhs_geo_region_dqpwygqj 0
hhs_geo_region_dqpwygqj 0

hhs_geo_region_fpwskwrf 0
hhs_geo_region_fpwskwrf 0

hhs_geo_region_kbazzjca 0
hhs_geo_region_kbazzjca 0

hhs_geo_region_lrircsnp 0
hhs_geo_region_lrircsnp 0

hhs_geo_region_lzgpxyit 0
hhs_geo_region_lzgpxyit 0

hhs_geo_region_mlyzmhmf 0
hhs_geo_region_mlyzmhmf 0

hhs_geo_region_oxchjgsf 0
hhs_geo_region_oxchjgsf 0

hhs_geo_region_qufhixun 0
hhs_geo_region_qufhixun 0

census_msa_MSA, Principle City 0
census_msa_MSA, Principle City 0

census_msa_Non-MSA 0
census_msa_Non-MSA 0

employment_industry_atmlpfrs 0
employment_industry_atmlpfrs 0

employment_industry_cfqqtusy 0
employment_industry_cfqqtusy 0

employment_industry_dotnnunm 0
employment_industry_dotnnunm 0

employment_industry_fcxhlnwr 0
employment_industry_fcxhlnwr 0

employment_industry_haxffmxo 0
employment_industry_haxffmxo 0

employment_industry_ldnlellj 0
employment_industry_ldnlellj 0

employment_industry_mcubkhph 0
employment_industry_mcubkhph 0

employment_industry_mfikgejo 0
employment_industry_mfikgejo 0

employment_industry_msuufmds 0
employment_industry_msuufmds 0

employment_industry_nduyfdeo 0
employment_industry_nduyfdeo 0

employment_industry_phxvnwax 0
employment_industry_phxvnwax 0

employment_industry_pxcmvdjn 0
employment_industry_pxcmvdjn 0

employment_industry_qnlwzans 0
employment_industry_qnlwzans 0

employment_industry_rucpziij 0
employment_industry_rucpziij 0

employment_industry_saaquncn 0
employment_industry_saaquncn 0

employment_industry_vjjrobsf 0
employment_industry_vjjrobsf 0

employment_industry_wlfvacwt 0
employment_industry_wlfvacwt 0

employment_industry_wxleyezf 0
employment_industry_wxleyezf 0

employment_industry_xicduogh 0
employment_industry_xicduogh 0

employment_industry_xqicxuve 0
employment_industry_xqicxuve 0

employment_industry_nan 0
employment_industry_nan 0

employment_occupation_ccgxvspp 0
employment_occupation_ccgxvspp 0

employment_occupation_cmhcxjea 0
employment_occupation_cmhcxjea 0

employment_occupation_dcjcmpih 0
employment_occupation_dcjcmpih 0

employment_occupation_dlvbwzss 0
employment_occupation_dlvbwzss 0

employment_occupation_emcorrxb 0
employment_occupation_emcorrxb 0

employment_occupation_haliazsg 0
employment_occupation_haliazsg 0

employment_occupation_hfxkjkmi 0
employment_occupation_hfxkjkmi 0

employment_occupation_hodpvpew 0
employment_occupation_hodpvpew 0

employment_occupation_kldqjyjy 0
employment_occupation_kldqjyjy 0

employment_occupation_mxkfnird 0
employment_occupation_mxkfnird 0

employment_occupation_oijqvulv 0
employment_occupation_oijqvulv 0

employment_occupation_pvmttkik 0
employment_occupation_pvmttkik 0

employment_occupation_qxajmpny 0
employment_occupation_qxajmpny 0

employment_occupation_rcertsgn 0
employment_occupation_rcertsgn 0

employment_occupation_tfqavkke 0
employment_occupation_tfqavkke 0

employment_occupation_ukymxvdu 0
employment_occupation_ukymxvdu 0

employment_occupation_uqqtjvyb 0
employment_occupation_uqqtjvyb 0

employment_occupation_vlluhbov 0
employment_occupation_vlluhbov 0

employment_occupation_xgwztkwe 0
employment_occupation_xgwztkwe 0

employment_occupation_xqwwgdyp 0
employment_occupation_xqwwgdyp 0

employment_occupation_xtkaffoo 0
employment_occupation_xtkaffoo 0

employment_occupation_xzmlyyjv 0
employment_occupation_xzmlyyjv 0

employment_occupation_nan 0
employment_occupation_nan 0

In [122]:
training_features= training_features.fillna(training_features.mean())

In [123]:
training_labels = pd.read_csv(r"C:\Users\Akshay Phatak\Documents\Atharva\ML\IITGuwati_Datascience\dataset and all\training_set_labels.csv")

In [124]:
training_labels_xyz = training_labels['xyz_vaccine']
training_labels__seasonal = training_labels['seasonal_vaccine']

In [125]:
from sklearn.model_selection import train_test_split
X_train_xyz, X_test_xyz, y_train_xyz, y_test_xyz = train_test_split(training_features,training_labels, test_size=0.21, random_state=21)